language: python
python: '3.5'
sudo: false
#required
env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all
  matrix:
    #- TOXENV=3.5-check
    #- TOXENV=docs

    #- TOXENV=2.7-cover,3.5-coveralls
    - TOXENV=2.7-nocover
    #- TOXENV=3.3-cover,3.5-coveralls
    - TOXENV=3.3-nocover
    #- TOXENV=3.4-cover,3.5-coveralls
    - TOXENV=3.4-nocover
    #- TOXENV=3.5-cover,3.5-coveralls
    - TOXENV=3.5-nocover
before_install:
  - python --version
  - uname -a
  - lsb_release -a
install:
  # - sudo apt-get -qq update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - export PY=${TOXENV:0:1}.${TOXENV:2:1}
  - export PYN=py${PY:0:1}${PY:2:1}
  # - export YML=./conda/conda-${PYN}.yml 
  - echo  $PY $PYN
  - echo  "$PY" "$PYN"
  # Replace dep1 dep2 ... with your dependencies
  - conda create -y -c anaconda --name $PYN python=$PY `head -n1 requirements_conda.txt`	
  - source activate $PYN 
  - python ./conda/installreq.py
  - python setup.py install
    # Builds Complete

  - pip install tox
  - virtualenv --version
  - easy_install --version
  - pip --version
  - pytest --version
  - tox --version
before-script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - pytest -x --tb=long -v
  - pytest --cov --cov-report=term-missing -vv
  -  coverage combine --append
  -  coverage report
  -  coveralls 

  # - travis_wait 30 tox -v
after_failure:
  #- more .tox/log/* | cat
  #- more .tox/*/log/* | cat
before_cache:
  - rm -rf $HOME/.cache/pip/log
cache:
  directories:
    - $HOME/.cache/pip
notifications:
  email:
    on_success: never
    on_failure: always
